export const teamActionType = {
	FETCH_START: "FETCH_START",
	GET_TEAMS: "GET_TEAMS",
	CREATE_TEAM: "CREATE_TEAM",
	FETCH_FAILURE: "FETCH_FAILURE",
	UPDATE_TEAM: "UPDATE_TEAM",
	ADD_TASK: "ADD_TASK",
	CLEAR_MSSG_RES: "CLEAR_MSSG_RES",
};
