export const userActionType = {
	AUTH_START: "AUTH_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
	AUTH_FAILURE: "AUTH_FAILURE",
	LOGOUT: "LOGOUT",
	CHECK_USER: "CHECK_USER",
	CLEAR_ERROR: "CLEAR_ERROR",
	UPDATE_AUTH_USER: "UPDATE_AUTH_USER",
};
