export const userActionType = {
	REQ_START: "REQ_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
	REQ_FAILURE: "REQ_FAILURE",
	LOGOUT: "LOGOUT",
	CHECK_USER: "CHECK_USER",
	UPDATE_AUTH_USER: "UPDATE_AUTH_USER",
	CLEAR_MSSG_USER: "CLEAR_MSSG_USER",
};
