export const taskActionType = {
	REQ_START_TASK: "REQ_START_TASK",
	REQ_SUCCESS_TASK: "REQ_SUCCESS_TASK",
	REQ_FAILURE_TASK: "REQ_FAILURE_TASK",
	SEPERATE_TASKS: "SEPERATE_TASKS",
	SHOW_TASK_WINDOW: "SHOW_TASK_WINDOW",
	LOAD_IMAGES: "LOAD_IMAGES",
	CLEAR_REQ_MSSG: "CLEAR_REQ_MSSG",
};
